steps:
  # Install deps
  - name: node:20
    entrypoint: npm
    args: ["ci"]

  # Build Frontend
  - name: node:20
    entrypoint: npm
    args: ["run", "build"]

  # Deploy to Firebase Hosting
  - name: gcr.io/firebase-build/firebase
    args: ["deploy", "--only", "hosting"]

options:
  logging: CLOUD_LOGGING_ONLY
